FROM golang:1.20-alpine AS build-stage
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY *.go .

RUN  CGO_ENABLED=0 GOOS=linux go build  -o /tungsten_go_exporter

FROM alpine:3.18
WORKDIR /
COPY --from=build-stage /tungsten_go_exporter /tungsten_go_exporter
CMD ["/tungsten_go_exporter","--config","/etc/tf_exporter.yaml"]